### PR TITLE
Add destream

### PR DESCRIPTION
**Pull request by s-zubov**

### CODE REVIEW

**Comment by dangershony** [comment]
Excellent does this include a docker hub image as well?

**Comment by s-zubov** [comment]
This is actually a source code for https://hub.docker.com/r/destream/coinvault. I guess you should include this image in coinvault docker hub, as it is uses https://hub.docker.com/r/coinvault/client-base image as base image.

**Comment by s-zubov** [comment]
Finally, `docker-compose up` and everything works.

**Comment by dangershony** [comment]
Keeping this open for a few more days.

**Pull request merged**
